### PR TITLE
fix: use `cjs` extension for cjs entrypoint

### LINKED ISSUE #73: parsel-js does not work with commonjs require
By using `"type": "module"` all cjs code needs to end with the correct extension. Currently trying to use parsel-js as cjs results in this error

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/lingga/selector-lint/node_modules/parsel-js/dist/cjs/parsel.min.js from /home/lingga/selector-lint/test.cjs not supported.
parsel.min.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename parsel.min.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /home/lingga/selector-lint/node_modules/parsel-js/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at Object.<anonymous> (/home/lingga/selector-lint/test.cjs:1:16) {
  code: 'ERR_REQUIRE_ESM'
}
```

### PR DESCRIPTION
**Pull request by ling1726**
Updates entrypoints and export maps for cjs to `parsel.min.cjs`

Fixes #73

### CODE REVIEW

**Comment by LeaVerou** [comment]
Fine with the change, though then we don't need a `/cjs/` directory at all, we can just have them directly in `/dist/`.

Any thoughts @jrandolf ?

**Comment by ling1726** [comment]
> Hey, thank you for contributing!
> 
> Fine with the change, though then we don't need a `/cjs/` directory at all, we can just have them directly in `/dist/`.
> 
> Any thoughts @jrandolf ?

Changing the dist folder output can happen anytime, right now the entire library  is unusable by anyone that needs to compile to cjs - which unfortunately includes webpack 🥲

**Comment by LeaVerou** [comment]
Sure, but isn't that a trivial change, since you're already working on this PR?

**Comment by ling1726** [comment]
> Sure, but isn't that a trivial change, since you're already working on this PR?

Oh sure, didn't realize you were asking me to do it, throught you were starting a round of discussion 😅

**Comment by LeaVerou** [comment]
> > Sure, but isn't that a trivial change, since you're already working on this PR?
> 
> Oh sure, didn't realize you were asking me to do it, throught you were starting a round of discussion 😅
> 
> Done in [2b149ac](https://github.com/LeaVerou/parsel/commit/2b149ac7fbd9a37dfcc9341a7342ba7ba69777b7)

Nah, it was more a "any objections?" 😁 
Thanks so much!

**Pull request merged**
