### PR TITLE
Setup Rollup 

### PR DESCRIPTION
**Pull request by rajasegar**
1. Move build artifacts to dist folder
2. Refer builds in package.json for various formats
3. Remove unnecessary files at project root
4. Remove custom build scripts
5. Add .gitignore to ignore node modules

### CODE REVIEW

**Comment by LeaVerou** [comment]
Hi there,

Thank you for working on this.
Have you verified that `parsel_nomodule.js` produced by Rollup is compatible with the existing one produced by the custom build script? It's hard to evaluate this with minification.

Other comments:
- I tend to create both minified and unminified bundles, it's only a few extra lines in the config
- We should also produce an ESM bundle, even if it's the same as the source file. a) Because in the future it may be pulling in other modules (or its own sub-modules) and b) so that a minified version can be created.

**Comment by rajasegar** [comment]
Yes, I have verified it in the browser and got the below results. Looks like Rollup is exporting the extra 4 constants with it. Hope it is fine.
## Existing `parsel_nomodule.js`:
```
Object.keys(parsel)
Array(8) [ "gobbleParens", "tokenizeBy", "tokenize", "nestTokens", "walk", "parse", "specificityToNumber", "specificity" ]
​
0: "gobbleParens"
​
1: "tokenizeBy"
​
2: "tokenize"
​
3: "nestTokens"
​
4: "walk"
​
5: "parse"
​
6: "specificityToNumber"
​
7: "specificity"
​
length: 8
​
<prototype>: Array []
```
## New Rollup generated `parsel_nomodule.js`
```
Object.keys(parsel)
Array(12) [ "RECURSIVE_PSEUDO_CLASSES", "RECURSIVE_PSEUDO_CLASSES_ARGS", "TOKENS", "TRIM_TOKENS", "gobbleParens", "nestTokens", "parse", "specificity", "specificityToNumber", "tokenize", … ]
​
0: "RECURSIVE_PSEUDO_CLASSES"
​
1: "RECURSIVE_PSEUDO_CLASSES_ARGS"
​
2: "TOKENS"
​
3: "TRIM_TOKENS"
​
4: "gobbleParens"
​
5: "nestTokens"
​
6: "parse"
​
7: "specificity"
​
8: "specificityToNumber"
​
9: "tokenize"
​
10: "tokenizeBy"
​
11: "walk"
​
length: 12
​
<prototype>: Array []
```

**Comment by rajasegar** [comment]
@LeaVerou Addressed the review comments, creating both unminified and minified versions, and esm bundles. 
Also I have added the exports field in package.json, could you please verify they are correct?

**Review by LeaVerou — CHANGES_REQUESTED** [review]
Thank you for making the changes.
Last nitpick (promise!): `parsel.js` should be the ESM version, as a more clear default, it should be everything else that has filename variations.

**Comment by rajasegar** [comment]
@LeaVerou Renamed the esm bundles, please take a look.

**Comment by LeaVerou** [comment]
Thank you! Sorry to be a pain, but why is the CJS one named `parsel.cmd.js`? Shouldn't it be `parsel.cjs.js`? Is this a convention I'm unaware of?

**Comment by rajasegar** [comment]
can we go with sub-folders like?
```
cjs/parsel.js
cjs/parsel.min.js
esm/parsel.js
esm/parsel.min.js
```
It's more convenient and intuitive.

**Comment by LeaVerou** [comment]
Sure, though I think ESM should be directly in `dist`.

**Comment by rajasegar** [comment]
@LeaVerou Made the changes accordingly, please check.

**Review by LeaVerou — APPROVED** [review]

**Comment by LeaVerou** [comment]
Merged, thank you!!

**Comment by LeaVerou** [comment]
Done!

**Comment by rajasegar** [comment]
@LeaVerou Thank you, checked the new version in my project, works fine.
https://github.com/rajasegar/ember-tailwind-codemod

**Pull request merged**
