### PR TITLE
Build `dist` during prepublishing

### PR DESCRIPTION
**Pull request by jrandolf**

### CODE REVIEW

**Comment by LeaVerou** [comment]
Thanks for the contribution!

Happy to remove build artifacts from the repo, but I'd need to setup hosting this on Netlify then which can run build tools, so that the bundles are still on the website and can still be linked through importing from a URL for those who wish to do that.

I just setup https://parsel.verou.me on Netify, would you mind updating the URLs in the docs to this one so it can be changed in one go once this PR is merged?

**Review by LeaVerou — CHANGES_REQUESTED** [review]
See comment

**Comment by jrandolf** [comment]
If that's the intended use-case, we can skip this commit.

**Comment by LeaVerou** [comment]
I'd rather we didn't, it's about time to remove build artifacts from this repo (I've been progressively moving all my repos from GH Pages to Netlify for this exact reason).

**Comment by LeaVerou** [comment]
I merged it, and I'll update the URL myself.

**Comment by jrandolf** [comment]
Ah, I see. I wasn't exactly sure what you meant by updating the URL since I don't use Netlify.

**Pull request merged**
